// All currencies supported by the ExchangeRate-API
export const CURRENCIES = [
  { code: 'USD', name: "US Dollar", symbol: "$", flag: '🇺🇸' },
  { code: 'AED', name: "United Arab Emirates Dirham", symbol: "AED", flag: '🇦🇪' },
  { code: 'AFN', name: "Afghan Afghani", symbol: "AFN", flag: '🇦🇫' },
  { code: 'ALL', name: "Albanian Lek", symbol: "ALL", flag: '🇦🇱' },
  { code: 'AMD', name: "Armenian Dram", symbol: "AMD", flag: '🇦🇲' },
  { code: 'ANG', name: "Netherlands Antillean Guilder", symbol: "ANG", flag: '🇨🇼' },
  { code: 'AOA', name: "Angolan Kwanza", symbol: "AOA", flag: '🇦🇴' },
  { code: 'ARS', name: "Argentine Peso", symbol: "ARS", flag: '🇦🇷' },
  { code: 'AUD', name: "Australian Dollar", symbol: "A$", flag: '🇦🇺' },
  { code: 'AWG', name: "Aruban Florin", symbol: "AWG", flag: '🇦🇼' },
  { code: 'AZN', name: "Azerbaijani Manat", symbol: "AZN", flag: '🇦🇿' },
  { code: 'BAM', name: "Bosnia-Herzegovina Convertible Mark", symbol: "BAM", flag: '🇧🇦' },
  { code: 'BBD', name: "Barbadian Dollar", symbol: "BBD", flag: '🇧🇧' },
  { code: 'BDT', name: "Bangladeshi Taka", symbol: "BDT", flag: '🇧🇩' },
  { code: 'BGN', name: "Bulgarian Lev", symbol: "BGN", flag: '🇧🇬' },
  { code: 'BHD', name: "Bahraini Dinar", symbol: "BHD", flag: '🇧🇭' },
  { code: 'BIF', name: "Burundian Franc", symbol: "BIF", flag: '🇧🇮' },
  { code: 'BMD', name: "Bermudan Dollar", symbol: "BMD", flag: '🇧🇲' },
  { code: 'BND', name: "Brunei Dollar", symbol: "BND", flag: '🇧🇳' },
  { code: 'BOB', name: "Bolivian Boliviano", symbol: "BOB", flag: '🇧🇴' },
  { code: 'BRL', name: "Brazilian Real", symbol: "R$", flag: '🇧🇷' },
  { code: 'BSD', name: "Bahamian Dollar", symbol: "BSD", flag: '🇧🇸' },
  { code: 'BTN', name: "Bhutanese Ngultrum", symbol: "BTN", flag: '🇧🇹' },
  { code: 'BWP', name: "Botswanan Pula", symbol: "BWP", flag: '🇧🇼' },
  { code: 'BYN', name: "Belarusian Ruble", symbol: "BYN", flag: '🇧🇾' },
  { code: 'BZD', name: "Belize Dollar", symbol: "BZD", flag: '🇧🇿' },
  { code: 'CAD', name: "Canadian Dollar", symbol: "CA$", flag: '🇨🇦' },
  { code: 'CDF', name: "Congolese Franc", symbol: "CDF", flag: '🇨🇩' },
  { code: 'CHF', name: "Swiss Franc", symbol: "CHF", flag: '🇨🇭' },
  { code: 'CLF', name: "Chilean Unit of Account (UF)", symbol: "CLF", flag: '🇨🇱' },
  { code: 'CLP', name: "Chilean Peso", symbol: "CLP", flag: '🇨🇱' },
  { code: 'CNH', name: "Chinese Yuan (offshore)", symbol: "CNH", flag: '🇨🇳' },
  { code: 'CNY', name: "Chinese Yuan", symbol: "CN¥", flag: '🇨🇳' },
  { code: 'COP', name: "Colombian Peso", symbol: "COP", flag: '🇨🇴' },
  { code: 'CRC', name: "Costa Rican Colón", symbol: "CRC", flag: '🇨🇷' },
  { code: 'CUP', name: "Cuban Peso", symbol: "CUP", flag: '🇨🇺' },
  { code: 'CVE', name: "Cape Verdean Escudo", symbol: "CVE", flag: '🇨🇻' },
  { code: 'CZK', name: "Czech Koruna", symbol: "CZK", flag: '🇨🇿' },
  { code: 'DJF', name: "Djiboutian Franc", symbol: "DJF", flag: '🇩🇯' },
  { code: 'DKK', name: "Danish Krone", symbol: "DKK", flag: '🇩🇰' },
  { code: 'DOP', name: "Dominican Peso", symbol: "DOP", flag: '🇩🇴' },
  { code: 'DZD', name: "Algerian Dinar", symbol: "DZD", flag: '🇩🇿' },
  { code: 'EGP', name: "Egyptian Pound", symbol: "EGP", flag: '🇪🇬' },
  { code: 'ERN', name: "Eritrean Nakfa", symbol: "ERN", flag: '🇪🇷' },
  { code: 'ETB', name: "Ethiopian Birr", symbol: "ETB", flag: '🇪🇹' },
  { code: 'EUR', name: "Euro", symbol: "€", flag: '🇪🇺' },
  { code: 'FJD', name: "Fijian Dollar", symbol: "FJD", flag: '🇫🇯' },
  { code: 'FKP', name: "Falkland Islands Pound", symbol: "FKP", flag: '🇫🇰' },
  { code: 'FOK', name: "FOK", symbol: "FOK", flag: '🇫🇴' },
  { code: 'GBP', name: "British Pound", symbol: "£", flag: '🇬🇧' },
  { code: 'GEL', name: "Georgian Lari", symbol: "GEL", flag: '🇬🇪' },
  { code: 'GGP', name: "GGP", symbol: "GGP", flag: '🇬🇬' },
  { code: 'GHS', name: "Ghanaian Cedi", symbol: "GHS", flag: '🇬🇭' },
  { code: 'GIP', name: "Gibraltar Pound", symbol: "GIP", flag: '🇬🇮' },
  { code: 'GMD', name: "Gambian Dalasi", symbol: "GMD", flag: '🇬🇲' },
  { code: 'GNF', name: "Guinean Franc", symbol: "GNF", flag: '🇬🇳' },
  { code: 'GTQ', name: "Guatemalan Quetzal", symbol: "GTQ", flag: '🇬🇹' },
  { code: 'GYD', name: "Guyanaese Dollar", symbol: "GYD", flag: '🇬🇾' },
  { code: 'HKD', name: "Hong Kong Dollar", symbol: "HK$", flag: '🇭🇰' },
  { code: 'HNL', name: "Honduran Lempira", symbol: "HNL", flag: '🇭🇳' },
  { code: 'HRK', name: "Croatian Kuna", symbol: "HRK", flag: '🇭🇷' },
  { code: 'HTG', name: "Haitian Gourde", symbol: "HTG", flag: '🇭🇹' },
  { code: 'HUF', name: "Hungarian Forint", symbol: "HUF", flag: '🇭🇺' },
  { code: 'IDR', name: "Indonesian Rupiah", symbol: "IDR", flag: '🇮🇩' },
  { code: 'ILS', name: "Israeli New Shekel", symbol: "₪", flag: '🇮🇱' },
  { code: 'IMP', name: "IMP", symbol: "IMP", flag: '🇮🇲' },
  { code: 'INR', name: "Indian Rupee", symbol: "₹", flag: '🇮🇳' },
  { code: 'IQD', name: "Iraqi Dinar", symbol: "IQD", flag: '🇮🇶' },
  { code: 'IRR', name: "Iranian Rial", symbol: "IRR", flag: '🇮🇷' },
  { code: 'ISK', name: "Icelandic Króna", symbol: "ISK", flag: '🇮🇸' },
  { code: 'JEP', name: "JEP", symbol: "JEP", flag: '🇯🇪' },
  { code: 'JMD', name: "Jamaican Dollar", symbol: "JMD", flag: '🇯🇲' },
  { code: 'JOD', name: "Jordanian Dinar", symbol: "JOD", flag: '🇯🇴' },
  { code: 'JPY', name: "Japanese Yen", symbol: "¥", flag: '🇯🇵' },
  { code: 'KES', name: "Kenyan Shilling", symbol: "KES", flag: '🇰🇪' },
  { code: 'KGS', name: "Kyrgyz Som", symbol: "KGS", flag: '🇰🇬' },
  { code: 'KHR', name: "Cambodian Riel", symbol: "KHR", flag: '🇰🇭' },
  { code: 'KID', name: "KID", symbol: "KID", flag: '🇰🇮' },
  { code: 'KMF', name: "Comorian Franc", symbol: "KMF", flag: '🇰🇲' },
  { code: 'KRW', name: "South Korean Won", symbol: "₩", flag: '🇰🇷' },
  { code: 'KWD', name: "Kuwaiti Dinar", symbol: "KWD", flag: '🇰🇼' },
  { code: 'KYD', name: "Cayman Islands Dollar", symbol: "KYD", flag: '🇰🇾' },
  { code: 'KZT', name: "Kazakhstani Tenge", symbol: "KZT", flag: '🇰🇿' },
  { code: 'LAK', name: "Laotian Kip", symbol: "LAK", flag: '🇱🇦' },
  { code: 'LBP', name: "Lebanese Pound", symbol: "LBP", flag: '🇱🇧' },
  { code: 'LKR', name: "Sri Lankan Rupee", symbol: "LKR", flag: '🇱🇰' },
  { code: 'LRD', name: "Liberian Dollar", symbol: "LRD", flag: '🇱🇷' },
  { code: 'LSL', name: "Lesotho Loti", symbol: "LSL", flag: '🇱🇸' },
  { code: 'LYD', name: "Libyan Dinar", symbol: "LYD", flag: '🇱🇾' },
  { code: 'MAD', name: "Moroccan Dirham", symbol: "MAD", flag: '🇲🇦' },
  { code: 'MDL', name: "Moldovan Leu", symbol: "MDL", flag: '🇲🇩' },
  { code: 'MGA', name: "Malagasy Ariary", symbol: "MGA", flag: '🇲🇬' },
  { code: 'MKD', name: "Macedonian Denar", symbol: "MKD", flag: '🇲🇰' },
  { code: 'MMK', name: "Myanmar Kyat", symbol: "MMK", flag: '🇲🇲' },
  { code: 'MNT', name: "Mongolian Tugrik", symbol: "MNT", flag: '🇲🇳' },
  { code: 'MOP', name: "Macanese Pataca", symbol: "MOP", flag: '🇲🇴' },
  { code: 'MRU', name: "Mauritanian Ouguiya", symbol: "MRU", flag: '🇲🇷' },
  { code: 'MUR', name: "Mauritian Rupee", symbol: "MUR", flag: '🇲🇺' },
  { code: 'MVR', name: "Maldivian Rufiyaa", symbol: "MVR", flag: '🇲🇻' },
  { code: 'MWK', name: "Malawian Kwacha", symbol: "MWK", flag: '🇲🇼' },
  { code: 'MXN', name: "Mexican Peso", symbol: "MX$", flag: '🇲🇽' },
  { code: 'MYR', name: "Malaysian Ringgit", symbol: "MYR", flag: '🇲🇾' },
  { code: 'MZN', name: "Mozambican Metical", symbol: "MZN", flag: '🇲🇿' },
  { code: 'NAD', name: "Namibian Dollar", symbol: "NAD", flag: '🇳🇦' },
  { code: 'NGN', name: "Nigerian Naira", symbol: "NGN", flag: '🇳🇬' },
  { code: 'NIO', name: "Nicaraguan Córdoba", symbol: "NIO", flag: '🇳🇮' },
  { code: 'NOK', name: "Norwegian Krone", symbol: "NOK", flag: '🇳🇴' },
  { code: 'NPR', name: "Nepalese Rupee", symbol: "NPR", flag: '🇳🇵' },
  { code: 'NZD', name: "New Zealand Dollar", symbol: "NZ$", flag: '🇳🇿' },
  { code: 'OMR', name: "Omani Rial", symbol: "OMR", flag: '🇴🇲' },
  { code: 'PAB', name: "Panamanian Balboa", symbol: "PAB", flag: '🇵🇦' },
  { code: 'PEN', name: "Peruvian Sol", symbol: "PEN", flag: '🇵🇪' },
  { code: 'PGK', name: "Papua New Guinean Kina", symbol: "PGK", flag: '🇵🇬' },
  { code: 'PHP', name: "Philippine Peso", symbol: "₱", flag: '🇵🇭' },
  { code: 'PKR', name: "Pakistani Rupee", symbol: "PKR", flag: '🇵🇰' },
  { code: 'PLN', name: "Polish Zloty", symbol: "PLN", flag: '🇵🇱' },
  { code: 'PYG', name: "Paraguayan Guarani", symbol: "PYG", flag: '🇵🇾' },
  { code: 'QAR', name: "Qatari Riyal", symbol: "QAR", flag: '🇶🇦' },
  { code: 'RON', name: "Romanian Leu", symbol: "RON", flag: '🇷🇴' },
  { code: 'RSD', name: "Serbian Dinar", symbol: "RSD", flag: '🇷🇸' },
  { code: 'RUB', name: "Russian Ruble", symbol: "RUB", flag: '🇷🇺' },
  { code: 'RWF', name: "Rwandan Franc", symbol: "RWF", flag: '🇷🇼' },
  { code: 'SAR', name: "Saudi Riyal", symbol: "SAR", flag: '🇸🇦' },
  { code: 'SBD', name: "Solomon Islands Dollar", symbol: "SBD", flag: '🇸🇧' },
  { code: 'SCR', name: "Seychellois Rupee", symbol: "SCR", flag: '🇸🇨' },
  { code: 'SDG', name: "Sudanese Pound", symbol: "SDG", flag: '🇸🇩' },
  { code: 'SEK', name: "Swedish Krona", symbol: "SEK", flag: '🇸🇪' },
  { code: 'SGD', name: "Singapore Dollar", symbol: "SGD", flag: '🇸🇬' },
  { code: 'SHP', name: "St. Helena Pound", symbol: "SHP", flag: '🇸🇭' },
  { code: 'SLE', name: "Sierra Leonean Leone", symbol: "SLE", flag: '🇸🇱' },
  { code: 'SLL', name: "Sierra Leonean Leone (1964—2022)", symbol: "SLL", flag: '🇸🇱' },
  { code: 'SOS', name: "Somali Shilling", symbol: "SOS", flag: '🇸🇴' },
  { code: 'SRD', name: "Surinamese Dollar", symbol: "SRD", flag: '🇸🇷' },
  { code: 'SSP', name: "South Sudanese Pound", symbol: "SSP", flag: '🇸🇸' },
  { code: 'STN', name: "São Tomé & Príncipe Dobra", symbol: "STN", flag: '🇸🇹' },
  { code: 'SYP', name: "Syrian Pound", symbol: "SYP", flag: '🇸🇾' },
  { code: 'SZL', name: "Swazi Lilangeni", symbol: "SZL", flag: '🇸🇿' },
  { code: 'THB', name: "Thai Baht", symbol: "THB", flag: '🇹🇭' },
  { code: 'TJS', name: "Tajikistani Somoni", symbol: "TJS", flag: '🇹🇯' },
  { code: 'TMT', name: "Turkmenistani Manat", symbol: "TMT", flag: '🇹🇲' },
  { code: 'TND', name: "Tunisian Dinar", symbol: "TND", flag: '🇹🇳' },
  { code: 'TOP', name: "Tongan Paʻanga", symbol: "TOP", flag: '🇹🇴' },
  { code: 'TRY', name: "Turkish Lira", symbol: "TRY", flag: '🇹🇷' },
  { code: 'TTD', name: "Trinidad & Tobago Dollar", symbol: "TTD", flag: '🇹🇹' },
  { code: 'TVD', name: "TVD", symbol: "TVD", flag: '🇹🇻' },
  { code: 'TWD', name: "New Taiwan Dollar", symbol: "NT$", flag: '🇹🇼' },
  { code: 'TZS', name: "Tanzanian Shilling", symbol: "TZS", flag: '🇹🇿' },
  { code: 'UAH', name: "Ukrainian Hryvnia", symbol: "UAH", flag: '🇺🇦' },
  { code: 'UGX', name: "Ugandan Shilling", symbol: "UGX", flag: '🇺🇬' },
  { code: 'UYU', name: "Uruguayan Peso", symbol: "UYU", flag: '🇺🇾' },
  { code: 'UZS', name: "Uzbekistani Som", symbol: "UZS", flag: '🇺🇿' },
  { code: 'VES', name: "Venezuelan Bolívar", symbol: "VES", flag: '🇻🇪' },
  { code: 'VND', name: "Vietnamese Dong", symbol: "₫", flag: '🇻🇳' },
  { code: 'VUV', name: "Vanuatu Vatu", symbol: "VUV", flag: '🇻🇺' },
  { code: 'WST', name: "Samoan Tala", symbol: "WST", flag: '🇼🇸' },
  { code: 'XAF', name: "Central African CFA Franc", symbol: "FCFA", flag: '🇨🇲' },
  { code: 'XCD', name: "East Caribbean Dollar", symbol: "EC$", flag: '🇦🇬' },
  { code: 'XCG', name: "Caribbean guilder", symbol: "Cg.", flag: '🇽🇨' },
  { code: 'XDR', name: "Special Drawing Rights", symbol: "XDR", flag: '🏦' },
  { code: 'XOF', name: "West African CFA Franc", symbol: "F CFA", flag: '🇸🇳' },
  { code: 'XPF', name: "CFP Franc", symbol: "CFPF", flag: '🇵🇫' },
  { code: 'YER', name: "Yemeni Rial", symbol: "YER", flag: '🇾🇪' },
  { code: 'ZAR', name: "South African Rand", symbol: "ZAR", flag: '🇿🇦' },
  { code: 'ZMW', name: "Zambian Kwacha", symbol: "ZMW", flag: '🇿🇲' },
  { code: 'ZWG', name: "Zimbabwean Gold", symbol: "ZWG", flag: '🇿🇼' },
  { code: 'ZWL', name: "Zimbabwean Dollar (2009–2024)", symbol: "ZWL", flag: '🇿🇼' },
];

/** Lookup a currency by its code. Returns undefined if not found. */
export function getCurrency(code) {
  if (!code) return undefined;
  return CURRENCIES.find(c => c.code === code.toUpperCase());
}
